version: '3.7'

services:
  oradb:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    volumes:
      - ./oradata/:/opt/oracle/oradata
    environment:
      - ORACLE_SID=ORCL
      - ORACLE_EDITIONa=Tester123_
      - ORACLE_EDITION=standard
    shm_size: '4g'
    ports:
      - 1521:1521
      - 5500:5500

  formsreports:
    build:
      context: OracleForms
      target: formsreports
    #entrypoint: sleep 9999999 # use this for own experiments, otherwise comment this
    volumes:
      - ./OracleForms/container-scripts/:/opt/container-scripts/
      #- ./user_projects/:/u01/oracle/user_projects # uncomment to persist generated domain config
    ports:
      - 7001:7001 # Weblogic (https for /console and /em)
      - 9011:9001 # FORMS
      - 9012:9002 # REPORTS

